### ISSUE TITLE
Error when mousing over frineds list on the bar

### ISSUE THREAD

**Issue by SmolderingEgo** [Kozoaku/XIV_Databar#12]
I have been trying to find a fix for months, I came across your version and tried it and I have the same issue.  I noticed the error text includes another addon so I delete it and tried again with no luck,  Both addons are using the same version of the LibQtip Minor 49

253x XIV_Databar\modules\micromenu.lua:549: attempt to index field '?' (a nil value)
[string "@XIV_Databar\modules\micromenu.lua"]:549: in function <XIV_Databar\modules\micromenu.lua:486>

Locals:
modifierFunc = <function> defined =[C]:-1
tooltip = <unnamed> {
 0 = <userdata>
 lines = <table> {
 }
 headerFont = GameTooltipHeaderText {
 }
 backdropInfo = <table> {
 }
 scripts = <table> {
 }
 TopRightCorner = <unnamed> {
 }
 TopLeftCorner = <unnamed> {
 }
 RightEdge = <unnamed> {
 }
 scrollFrame = <unnamed> {
 }
 BottomLeftCorner = <unnamed> {
 }
 height = 293.231873
 columns = <table> {
 }
 cell_margin_v = 3
 TopEdge = <unnamed> {
 }
 BottomEdge = <unnamed> {
 }
 regularFont = GameTooltipText {
 }
 width = 390.726509
 cell_margin_h = 6
 colspans = <table> {
 }
 labelProvider = <table> {
 }
 key = "SocialToolTip"
 BottomRightCorner = <unnamed> {
 }
 scrollChild = <unnamed> {
 }
 LeftEdge = <unnamed> {
 }
 Center = <unnamed> {
 }
}
_ = 119
totalBNOnlineFriends = 44
totalOnlineFriends = 0
playerFaction = "Alliance"
r = 0
g = 0.439215
b = 0.866665
(for index) = 13
(for limit) = 119
(for step) = 1
i = 13
friendAccInfo = <table> {
 isFriend = true
 isDND = false
 isFavorite = false
 gameAccountInfo = <table> {
 }
 accountName = "|Kq24|k"
 battleTag = "Aggreaux#1500"
 note = ""
 rafLinkType = 0
 bnetAccountID = 25
 appearOffline = false
 customMessage = ""
 lastOnlineTime = 1628909456
 customMessageTime = 0
 isAFK = false
 isBattleTagFriend = true
}
gameAccount = <table> {
 isGameAFK = false
 clientProgram = "OSI"
 richPresence = "Act I - Normal"
 isGameBusy = false
 gameAccountID = 189
 isWowMobile = false
 isInCurrentRegion = false
 regionID = 56
 hasFocus = true
 canSummon = false
 isOnline = true
}
charName = nil
gameClient = "OSI"
realmName = nil
faction = nil
zone = nil
richPresence = "Act I - Normal"
isWoW = false
isClassic = false
statusIcon = "FriendsFrame\StatusIcon-Online"
socialIcon = "FriendsFrame\Battlenet-DiabloIIResurrectedicon"
(*temporary) = nil
(*temporary) = "FriendsFrame\Battlenet-DiabloIIResurrectedicon"
(*temporary) = "(|cffecd672Mísfìt-Perenolde|r)"
(*temporary) = <table> {
 1 = "WoW"
 2 = "S2"
 3 = "D3"
 4 = "WTCG"
 5 = "Hero"
 6 = "Pro"
 7 = "S1"
 8 = "DST2"
 9 = "VIPR"
 10 = "ODIN"
 11 = "LAZR"
 12 = "ZEUS"
 13 = "W3"
}
(*temporary) = "|TFriendsFrame\StatusIcon-Online:16|t|cff82c5ff |Kq76|k|r "
(*temporary) = "(|cffecd672Mísfìt-Perenolde|r) The Maw |TFriendsFrame\Battlenet-WoWicon:16|t"
(*temporary) = <function> defined @BartrubySummonPet\libs\LibQTip-1.0\LibQTip-1.0.lua:1420
(*temporary) = <unnamed> {
 0 = <userdata>
 lines = <table> {
 }
 headerFont = GameTooltipHeaderText {
 }
 backdropInfo = <table> {
 }
 scripts = <table> {
 }
 TopRightCorner = <unnamed> {
 }
 TopLeftCorner = <unnamed> {
 }
 RightEdge = <unnamed> {
 }
 scrollFrame = <unnamed> {
 }
 BottomLeftCorner = <unnamed> {
 }
 height = 293.231873
 columns = <table> {
 }
 cell_margin_v = 3
 TopEdge = <unnamed> {
 }
 BottomEdge = <unnamed> {
 }
 regularFont = GameTooltipText {
 }
 width = 390.726509
 cell_margin_h = 6
 colspans = <table> {
 }
 labelProvider = <table> {
 }
 key = "SocialToolTip"
 BottomRightCorner = <unnamed> {
 }
 scrollChild = <unnamed> {
 }
 LeftEdge = <unnamed> {
 }
 Center = <unnamed> {
 }
}
(*temporary) = 14
(*temporary) = "OnMouseUp"
(*temporary) = <function> defined @XIV_Databar\modules\micromenu.lua:615
(*temporary) = nil
(*temporary) = <function> defined @BartrubySummonPet\libs\LibQTip-1.0\LibQTip-1.0.lua:1366
(*temporary) = <unnamed> {
 0 = <userdata>
 OnBackdropLoaded = <function> defined @SharedXML\Backdrop.lua:205
 GetBackdropColor = <function> defined @SharedXML\Backdrop.lua:443
 SetupTextureCoordinates = <function> defined @SharedXML\Backdrop.lua:267
 OnBackdropSizeChanged = <function> defined @SharedXML\Backdrop.lua:235
 HasBackdropInfo = <function> defined @SharedXML\Backdrop.lua:331
 SetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:475
 _OnMouseUp_func = <function> defined @XIV_Databar\modules\micromenu.lua:615
 GetEdgeSize = <function> defined @SharedXML\Backdrop.lua:241
 _OnEnter_func = <func

**Comment by Kozoaku** [comment]
I'm not able to reproduce this. Can you please download the latest version (3.0.20), disable all other addons, and try again? I would like to fix this for you.

**Comment by randompsique** [comment]
Not sure if I'm gonna help but this used to happen to me when one of my friends on BNET was playing Diablo Immortal, it also happened before when new COD came out but then it was fixed. Hope it can help you fixing it, thanks!

**Comment by mikaeleg** [comment]
I have fixed this myself by chaging the micromenu.lua at line 549 with the following:

local gameName=''
if MenuModule.socialIcons[gameClient] then
  gameName = MenuModule.socialIcons[gameClient].text
end

This will make it so if socialIcons list is not updated with all the new games on battle.net it will just show the gameName as nothing. It will show the friend as being online but won't say which game the friend is playing. I was thinking of just using gameClient instead in that case, but the recent gameClient ids are just weird and doesnt really help (might help if you wish to update the social icon list to see which id you need to add).
