### ISSUE TITLE
Does this work for Retail wow or Classic?

### ISSUE THREAD

**Issue by Dimmnn** [Kozoaku/XIV_Databar#19]
So i found this fork from the Vicious comment. I tried to install this on Retail but im getting a lot of LUA errors. I wasnt sure if this was being updated for DragonFlight?

**Comment by Kozoaku** [comment]
It should work fine on Retail. If you are getting errors, please turn off all other addons and send the error stack that you get along with what you did to recreate the error. That will be the most helpful in debugging issues.

I am in the process of creating a version for Wrath Classic prior to release next week but there are lots of sections of the code that rely on interfaces and functions added after Wrath.
