### ISSUE TITLE
Dragonflight Beta Fixes

### ISSUE THREAD

**Issue by ETSeki** [Kozoaku/XIV_Databar#22]
Hello thanks for keeping this addon alive. Just wwanted to share the bugs i experienced in DF Beta nad their fixes.
1.
Interface/AddOns/XIV_Databar/modules/gold.lua:152: attempt to call global 'GetContainerNumFreeSlots' (a nil value)

Just replace
      freeSpace = freeSpace + GetContainerNumFreeSlots(i)
with
      freeSpace = freeSpace + C_Container.GetContainerNumFreeSlots(i)

2.
Interface/AddOns/XIV_Databar/core.lua:380: attempt to call global 'PlayerFrame_IsAnimatedOut' (a nil value)
sadly i couldnt find a replacement for this function and i also dont realy know whats is purpose is so i just deleted it and it seems to be fine.
Edit. This leads to a bugged out target frame also there are no LUA errors. Im trying to find an alternative to the deleted function.

3.
Interface/AddOns/XIV_Databar/modules/tradeskill.lua:199: attempt to call field 'GetTradeSkillLine' (a nil value)
You can just replace
      local _, _, _, _, _, openSkillLine, _ = C_TradeSkillUI.GetTradeSkillLine()
with
      local openSkillLine = C_TradeSkillUI.GetBaseProfessionInfo().professionID

**Comment by Kozoaku** [comment]
Thanks for this! I really appreciate you doing the work to debug before submitting the issue.

**Comment by penwebau** [comment]
I also had bug #2 from above

I changed line 380 in core.lua from 

`if (PlayerFrame and not PlayerFrame:IsUserPlaced() and not PlayerFrame_IsAnimatedOut(PlayerFrame)) then`

to 

`if (PlayerFrame and not PlayerFrame:IsUserPlaced()) then`

and it appears to have fixed this bug.
