### ISSUE TITLE
Errors 10.0 pre patch

### ISSUE THREAD

**Issue by kasiopec** [Kozoaku/XIV_Databar#23]
1. happens when mouseovering friends list

```
Stack: Interface/AddOns/XIV_Databar/modules/micromenu.lua:566: attempt to call global 'BNet_GetClientTexture' (a nil value)
[string "=[C]"]: in function `BNet_GetClientTexture'
[string "@Interface/AddOns/XIV_Databar/modules/micromenu.lua"]:566: in function <Interface/AddOns/XIV_Databar/modules/micromenu.lua:504>
```

2. Also I have a strange bug that when I press on hearthstone items they do nothing.

**Comment by mikaeleg** [comment]
Think you need to change that call with the BNet_GetClientEmbeddedAtlas call.
Forum post about the change:
https://us.forums.blizzard.com/en/blizzard/t/breaking-framexml-change-in-dragonflight-api/35736
