### ISSUE TITLE
Prepatch Error

### ISSUE THREAD

**Issue by Reanimatez** [Kozoaku/XIV_Databar#24]
Addon disappears on login and reload, can only make it visible by enabling and disabling "hide when in combat".
![image](https://user-images.githubusercontent.com/116766561/198145240-681248e0-cca7-461e-af2a-e85152a5984e.png)

**Comment by penwebau** [comment]
@Reanimatez I was having the same issue - I deleted all .lua files related to xiv_databar from my WTF folder and restarted and it was all good.

**Comment by penwebau** [comment]
Same for me - in fact adjusting or changing any option makes it visible.
