### ISSUE TITLE
Travel Modules not working

### ISSUE THREAD

**Issue by Dimmnn** [Kozoaku/XIV_Databar#25]
When I try to change the Travel Modules by right clicking on the hearthstones to switch them to the Acherus nothing happens. I don't get any LUA errors, it just doesnt do anything. I can't even left click on the far right hearth stone and it will not hearth me.

Thanks for updating this..

**Comment by ETSeki** [comment]
This can be fixed by replacing ("AnyUP") with ("AnyUp", "AnyDown") in line 130 and 134 of the travel.lua
More information on why this is needed can be found here
https://github.com/Stanzilla/WoWUIBugs/issues/268
