### ISSUE TITLE
Hey Kozoaku ! Thanks 

### ISSUE THREAD

**Issue by DFakto** [Kozoaku/XIV_Databar#27]
Turns out GitHuib doesn't allow personal messages, so here we are.
I just wanted to say thanks for the great work keeping XIV Databar alive, is one of my favorite addons ever.
There are some issues with it in DragonFlight, but I see you are already on top of it.
Keep the fantastic work mate! Long live the XIV !

**Comment by Kozoaku** [comment]
Thanks! Messages like these are always encouraging.
