### ISSUE TITLE
Tradeskills Lua Error Clicking on Tradeskills in databar.

### ISSUE THREAD

**Issue by Dimmnn** [Kozoaku/XIV_Databar#28]
I'm getting this error when I click on my Alchemy trade skill in the data bar.

1x [ADDON_ACTION_BLOCKED] AddOn 'TradeSkillMaster' tried to call the protected function 'UNKNOWN()'.
[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `CraftRecipe'
[string "@Interface/AddOns/Blizzard_Professions/Blizzard_ProfessionsCrafting.lua"]:707: in function <...lizzard_Professions/Blizzard_ProfessionsCrafting.lua:706>
[string "@Interface/AddOns/Blizzard_Professions/Blizzard_ProfessionsCrafting.lua"]:766: in function `craftingCallback'
[string "@Interface/AddOns/Blizzard_Professions/Blizzard_ProfessionsCrafting.lua"]:653: in function `ContinueCrafting'
[string "@Interface/AddOns/Blizzard_Professions/Blizzard_ProfessionsCrafting.lua"]:116: in function <...lizzard_Professions/Blizzard_ProfessionsCrafting.lua:110>

**Comment by Kozoaku** [comment]
This is an error with TradeSkillMaster. Please use their [guidelines](https://support.tradeskillmaster.com/en_US/addon/how-do-i-report-an-issue-i-have-with-tsm) for reporting an issue.
