### ISSUE TITLE
Friend list mouseover not working since prepatch

### ISSUE THREAD

**Issue by randompsique** [Kozoaku/XIV_Databar#31]
Hi! Thanks for keeping this addon updated.
For me, since prepatch friend list mouseover isn't working, it doesn't show anything and it throws LUA error.

Message: Interface/AddOns/XIV_Databar/modules/micromenu.lua:566: attempt to call global 'BNet_GetClientTexture' (a nil value)
Time: Tue Nov  8 12:48:42 2022
Count: 5
Stack: Interface/AddOns/XIV_Databar/modules/micromenu.lua:566: attempt to call global 'BNet_GetClientTexture' (a nil value)
[string "@Interface/AddOns/TradeSkillMaster/LibTSM/Service/ErrorHandler.lua"]:769: in function <...Ons/TradeSkillMaster/LibTSM/Service/ErrorHandler.lua:725>
[string "=[C]"]: in function `BNet_GetClientTexture'
[string "@Interface/AddOns/XIV_Databar/modules/micromenu.lua"]:566: in function <Interface/AddOns/XIV_Databar/modules/micromenu.lua:504>

Locals: errMsg = "Interface/AddOns/XIV_Databar/modules/micromenu.lua:566: attempt to call global 'BNet_GetClientTexture' (a nil value)"
isBugGrabber = nil
tsmErrMsg = nil
oldModule = nil
private = <table> {
 globalNameTranslation = <table> {
 }
 FormatErrorMessageSection = <function> defined @Interface/AddOns/TradeSkillMaster/LibTSM/Service/ErrorHandler.lua:525
 ErrorHandler = <function> defined @Interface/AddOns/TradeSkillMaster/LibTSM/Service/ErrorHandler.lua:134
 origErrorHandler = <function> defined @Interface/SharedXML/SharedBasicControls.lua:360
 hitInternalError = false
 CreateErrorFrame = <function> defined @Interface/AddOns/TradeSkillMaster/LibTSM/Service/ErrorHandler.lua:544
 num = 0
 SanitizeString = <function> defined @Interface/AddOns/TradeSkillMaster/LibTSM/Service/ErrorHandler.lua:518
 AddonBlockedHandler = <function> defined @Interface/AddOns/TradeSkillMaster/LibTSM/Service/ErrorHandler.lua:502
 GetStackLevelInfo = <function> defined @Interface/AddOns/TradeSkillMaster/LibTSM/Service/ErrorHandler.lua:344
 ParseLocals = <function> defined @Interface/AddOns/TradeSkillMaster/LibTSM/Service/ErrorHandler.lua:396
 ignoreErrors = false
 errorReports = <table> {
 }
 IsTSMAddon = <function> defined @Interface/AddOns/TradeSkillMaster/LibTSM/Service/ErrorHandler.lua:478
 localLinesTemp = <table> {
 }
 GetStackInfo = <function> defined @Interface/AddOns/TradeSkillMaster/LibTSM/Service/ErrorHandler.lua:313
}
MAX_STACK_DEPTH = 50
OLD_TSM_MODULES = <table> {
 1 = "TradeSkillMaster_Accounting"
 2 = "TradeSkillMaster_AuctionDB"
 3 = "TradeSkillMaster_Auctioning"
 4 = "TradeSkillMaster_Crafting"
 5 = "TradeSkillMaster_Destroying"
 6 = "TradeSkillMaster_Mailing"
 7 = "TradeSkillMaster_Shopping"
 8 = "TradeSkillMaster_Vendoring"
 9 = "TradeSkillMaster_Warehousing"
}

**Comment by Kozoaku** [comment]
Closed by PR #41
