### ISSUE TITLE
XIV_Databar has been blocked from an action only available to the Blizzard UI

### ISSUE THREAD

**Issue by dadeel** [Kozoaku/XIV_Databar#32]
Sometimes when I change instances I can no longer use my keybinds. I get this error and I have to reload my UI. I don't get any LUA errors just this popup. Thanks for the help.

**Comment by Kozoaku** [comment]
I'm having trouble replicating this. Could you please take a screenshot of your UI the next time it happens? 

Also, I suggest using BugSack to get the Lua errors. It requires BugGrabber to be installed as well but they are both very small and unobtrusive. There is small minimap icon that changes from green to red once an error has been caught and blocks the default Lua Error dialog from opening. I find that it also grabs those invisible errors like the one you are describing.

**Comment by dadeel** [comment]
Thanks for the help on this addon. Here is a picture of the error I get. I
installed BugSack and there are some error messages.

2x [ADDON_ACTION_FORBIDDEN] AddOn 'XIV_Databar' tried to call the protected
function 'UseAction()'.
[string ***@***.***/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function
<Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `UseAction'
[string ***@***.***/FrameXML/SecureTemplates.lua"]:364: in function
`handler'
[string ***@***.***/FrameXML/SecureTemplates.lua"]:690: in function
<Interface/FrameXML/SecureTemplates.lua:672>
[string ***@***.***/FrameXML/SecureTemplates.lua"]:704: in function
<Interface/FrameXML/SecureTemplates.lua:697>
[string ***@***.***/FrameXML/SecureTemplates.lua"]:746: in function
`SecureActionButton_OnClick'
[string ***@***.***/FrameXML/ActionButton.lua"]:109: in function
`TryUseActionButton'
[string ***@***.***/FrameXML/ActionButton.lua"]:144: in function
`ActionButtonDown'
[string "ACTIONBUTTON9"]:2: in function <[string "ACTIONBUTTON9"]:1>

**Comment by Kozoaku** [comment]
I haven't been able to reproduce and no other reports of this have come in. If it appears again, please re-open this issue or create a new one.
