### ISSUE TITLE
Everything gold related seems to be bugged

### ISSUE THREAD

**Issue by randompsique** [Kozoaku/XIV_Databar#37]
Everytime you post an auction, or receive gold in any form sends a LUA error. Also the gold module in the micromenu seems to be gone.

Message: Interface/AddOns/XIV_Databar/modules/gold.lua:152: attempt to call global 'GetContainerNumFreeSlots' (a nil value)
Time: Tue Nov 15 20:29:32 2022
Count: 38
Stack: Interface/AddOns/XIV_Databar/modules/gold.lua:152: attempt to call global 'GetContainerNumFreeSlots' (a nil value)
[string "@Interface/AddOns/TradeSkillMaster/LibTSM/Service/ErrorHandler.lua"]:769: in function <...Ons/TradeSkillMaster/LibTSM/Service/ErrorHandler.lua:725>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/XIV_Databar/modules/gold.lua"]:152: in function `Refresh'
[string "@Interface/AddOns/XIV_Databar/modules/gold.lua"]:269: in function `?'
[string "@Interface/AddOns/Masque/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:114: in function <...que/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:114>
[string "=[C]"]: ?
[string "@Interface/AddOns/Masque/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:24: in function <...que/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:20>
[string "@Interface/AddOns/Masque/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:59: in function `Fire'
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <...UI_Libraries/Core/Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals: <none>

**Comment by ETSeki** [comment]
I made a pull request with a fix for this. Till then you can just change GetContainerNumFreeSlots to C_Container.GetContainerNumFreeSlots
