### ISSUE TITLE
Is there any way to get the devs release?

### ISSUE THREAD

**Issue by randompsique** [Kozoaku/XIV_Databar#40]
Hi, sorry for being a bit obnoxious, I have noticed you are addressing lots of issues but release version remains the same, I guess this is because you want to get as much done as possible before next release.

I don't know nothing about coding nor github nor anything related. But I would like to know if there is a way I could be using the version that devs are working on, or should I just wait until another version is released.

Sorry  again for being annoying, is just that right now it's impossible to play with the addon enabled the way it is. Thanks a lot.

**Comment by Kozoaku** [comment]
I've been squashing bugs as quick as possible. There was a few fixes that needed to wait for 10.0.02 due to changes in the API. I am doing a release right now.

**Comment by Kozoaku** [comment]
I should also get in the habit of making beta releases for when I fix a bug but am not ready to release yet. That way people like you can get the benefit of my bug fixes and test new features prior to general availability. 

If you use WoWUp, you can change the channel to Beta or Alpha, depending on how cutting edge you want to be.
