### ISSUE TITLE
Addon doesn't load if set to Top

### ISSUE THREAD

**Issue by Reanimatez** [Kozoaku/XIV_Databar#42]
It'll load if I have it set to show at the bottom of the screen, but not at the top.

**Comment by Kozoaku** [comment]
This was fixed using the BigWigs Packager's ability to comment code sections out during packaging. Looking at my install, I see that the offending code was not commented out. I am pushing a patch shortly that uses the WOW_PROJECT_ID to detect if the current client is retail.
