### ISSUE TITLE
Social Icon change doesn't work.

### ISSUE THREAD

**Issue by katur239** [Kozoaku/XIV_Databar#45]
Changes to the Social Window Icon doesn't work. See screenshot below

![image](https://user-images.githubusercontent.com/10789738/202360147-2c3430e9-9344-447a-9e4d-fd40a4812259.png)

I found the old function and if you add it into the code it works again. Don't know if it's the best solution but it works.

`function BNet_GetClientTexture(client)
  if ( client == BNET_CLIENT_WOW ) then
    return "Interface\\FriendsFrame\\Battlenet-WoWicon";
  elseif ( client == BNET_CLIENT_SC2 ) then
    return "Interface\\FriendsFrame\\Battlenet-Sc2icon";
  elseif ( client == BNET_CLIENT_D3 ) then
    return "Interface\\FriendsFrame\\Battlenet-D3icon";
  elseif ( client == BNET_CLIENT_WTCG ) then
    return "Interface\\FriendsFrame\\Battlenet-WTCGicon";
  elseif ( client == BNET_CLIENT_HEROES ) then
    return "Interface\\FriendsFrame\\Battlenet-HotSicon";
  elseif ( client == BNET_CLIENT_OVERWATCH ) then
    return "Interface\\FriendsFrame\\Battlenet-Overwatchicon";
  elseif ( client == BNET_CLIENT_SC ) then
    return "Interface\\FriendsFrame\\Battlenet-SCicon";
  elseif ( client == BNET_CLIENT_DESTINY2 ) then
    return "Interface\\FriendsFrame\\Battlenet-Destiny2icon";
  elseif ( client == BNET_CLIENT_COD ) then
    return "Interface\\FriendsFrame\\Battlenet-CallOfDutyBlackOps4icon";
  elseif ( client == BNET_CLIENT_COD_MW ) then
    return "Interface\\FriendsFrame\\Battlenet-CallOfDutyMWicon";
  elseif ( client == BNET_CLIENT_COD_MW2 ) then
    return "Interface\\FriendsFrame\\Battlenet-CallOfDutyMW2icon";
  elseif ( client == BNET_CLIENT_COD_BOCW ) then
    return "Interface\\FriendsFrame\\Battlenet-CallOfDutyBlackOpsColdWaricon";
  elseif ( client == BNET_CLIENT_WC3 ) then
    return "Interface\\FriendsFrame\\Battlenet-Warcraft3Reforged";
  elseif ( client == BNET_CLIENT_ARCADE ) then
    return "Interface\\FriendsFrame\\Battlenet-BlizzardArcadeCollectionicon";
  elseif ( client == BNET_CLIENT_CRASH4 ) then
    return "Interface\\FriendsFrame\\Battlenet-CrashBandicoot4icon";
  elseif ( client == BNET_CLIENT_D2 ) then
    return "Interface\\FriendsFrame\\Battlenet-DiabloIIResurrectedicon";
  elseif ( client == BNET_CLIENT_COD_VANGUARD ) then
    return "Interface\\FriendsFrame\\Battlenet-CallOfDutyVanguardicon";
  elseif ( client == BNET_CLIENT_DI) then
    return "Interface\\FriendsFrame\\Battlenet-DiabloImmortalicon";
  elseif ( client == BNET_CLIENT_ARCLIGHT) then
    return "Interface\\FriendsFrame\\Battlenet-WarcraftArclightRumbleicon";
  else
    return "Interface\\FriendsFrame\\Battlenet-Battleneticon";
  end
end`

**Comment by Kozoaku** [comment]
Blizzard removed the BNet_GetClientTexture function in 10.0.2 which prevented the social window from opening. I will work on a solution to remove the |T and :16 and just display the person icon. 

That is the correct icon for friends who have either the mobile app or desktop app open and are not logged into a specific game.

**Comment by Kozoaku** [comment]
Please check out the 3.0.27 beta version to make sure everything works as you expect. You can download it from [Wago](https://addons.wago.io/addons/xiv-databar/versions?stability=beta) or set your release channel as Beta in WoWUp.
