### ISSUE TITLE
Hide options don't work

### ISSUE THREAD

**Issue by ThePrez0Dent** [Kozoaku/XIV_Databar#47]
The option to hide the bar in combat doesn't work, as does the option to hide in flight
Only this addon and BugGrabber/Sack active.

-------------------------------------------------------------------------------------------------------------------------------
1x Interface/AddOns/XIV_Databar/core.lua:262: attempt to call method 'IsVisible' (a nil value)
[string "@Interface/AddOns/XIV_Databar/core.lua"]:262: in function <Interface/AddOns/XIV_Databar/core.lua:261>
[string "=[C]"]: ?

Locals:
_ = XIV_Databar {
 0 = <userdata>
}
event = "PLAYER_REGEN_DISABLED"
(*temporary) = nil
(*temporary) = <table> {
 defaults = <table> {
 }
 ResetUI = <function> defined @Interface/AddOns/XIV_Databar/core.lua:390
 HoverColors = <function> defined @Interface/AddOns/XIV_Databar/core.lua:184
 HexToRGBA = <function> defined @Interface/AddOns/XIV_Databar/core.lua:341
 modules = <table> {
 }
 baseName = "XIV_Databar"
 IterateEmbeds = <function> defined @Interface/AddOns/XIV_Databar/Libs/AceAddon-3.0/AceAddon-3.0.lua:438
 GetColor = <function> defined @Interface/AddOns/XIV_Databar/core.lua:168
 fontFlags = <table> {
 }
 GetTextColorOptions = <function> defined @Interface/AddOns/XIV_Databar/core.lua:588
 RegisterFrame = <function> defined @Interface/AddOns/XIV_Databar/core.lua:198
 Printf = <function> defined @Interface/AddOns/XIV_Databar/Libs/AceConsole-3.0/AceConsole-3.0.lua:65
 SetDefaultModulePrototype = <function> defined @Interface/AddOns/XIV_Databar/Libs/AceAddon-3.0/AceAddon-3.0.lua:405
 GetHeight = <function> defined @Interface/AddOns/XIV_Databar/core.lua:278
 defaultModuleState = true
 IsEnabled = <function> defined @Interface/AddOns/XIV_Databar/Libs/AceAddon-3.0/AceAddon-3.0.lua:447
 DisableModule = <function> defined @Interface/AddOns/XIV_Databar/Libs/AceAddon-3.0/AceAddon-3.0.lua:346
 GetFont = <function> defined @Interface/AddOns/XIV_Databar/core.lua:324
 PrintTable = <function> defined @Interface/AddOns/XIV_Databar/core.lua:349
 RegisterMessage = <function> defined @Interface/AddOns/BugSack/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:90
 GetArgs = <function> defined @Interface/AddOns/XIV_Databar/Libs/AceConsole-3.0/AceConsole-3.0.lua:140
 frames = <table> {
 }
 miniTextPosition = "TOP"
 db = <table> {
 }
 modulesOptionFrame = Frame {
 }
 SetEnabledState = <function> defined @Interface/AddOns/XIV_Databar/Libs/AceAddon-3.0/AceAddon-3.0.lua:420
 enabledState = true
 RegisterEvent = <function> defined @Interface/AddOns/BugSack/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:90
 IterateModules = <function> defined @Interface/AddOns/XIV_Databar/Libs/AceAddon-3.0/AceAddon-3.0.lua:433
 GetClassColors = <function> defined @Interface/AddOns/XIV_Databar/core.lua:328
 SetColor = <function> defined @Interface/AddOns/XIV_Databar/core.lua:159
 OnInitialize = <function> defined @Interface/AddOns/XIV_Databar/core.lua:81
 NewModule = <function> defined @Interface/AddOns/XIV_Databar/Libs/AceAddon-3.0/AceAddon-3.0.lua:231
 GetModule = <function> defined @Interface/AddOns/XIV_Databar/Libs/AceAddon-3.0/AceAddon-3.0.lua:206
 defaultModuleLibraries = <table> {
 }
 optionsFrame = Frame {
 }
 GetTextOptions = <function> defined @Interface/AddOns/XIV_Databar/core.lua:538
 UnregisterChatCommand = <function> defined @Interface/AddOns/XIV_Databar/Libs/AceConsole-3.0/AceConsole-3.0.lua:107
 GetName = <function> defined @Interface/AddOns/XIV_Databar/Libs/AceAddon-3.0/AceAddon-3.0.lua:275
 name = "XIV_Databar"
 HideBarEvent = <function> defined @Interface/AddOns/XIV_Databar/core.lua:219
 orderedModules = <table> {
 }
 CreateMainBar = <function> defined @Interface/AddOns/XIV_Databar/core.lua:212
 Disable = <function> defined @Interface/AddOns/XIV_Databar/Libs/AceAddon-3.0/AceAddon-3.0.lua:310
 LSM = <table> {
 }
 Print = <function> defined @Interface/AddOns/XIV_Databar/Libs/AceConsole-3.0/AceConsole-3.0.lua:50
 constants = <table> {
 }
 IsModule = <function> defined @Interface/AddOns/XIV_Databar/Libs/AceAddon-3.0/AceAddon-3.0.lua:464
 SendMessage = <function> defined @Interface/AddOns/BugSack/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:59
 timerRefresh = true
 profilesOptionFrame = Frame {
 }
 OnEnable = <function> defined @Interface/AddOns/XIV_Databar/core.lua:137
 SetDefaultModuleLibraries = <function> defined @Interface/AddOns/XIV_Databar/Libs/AceAddon-3.0/AceAddon-3.0.lua:363
 Enable = <function> defined @Interface/AddOns/XIV_Databar/Libs/AceAddon-3.0/AceAddon-3.0.lua:290
 RegisterChatCommand = <function> defined @Interface/AddOns/XIV_Databar/Libs/AceConsole-3.0/AceConsole-3.0.lua:81
 EnableModule = <function> defined @Interface/AddOn

-------------------------------------------------------------------------------------------------------------------------------
1x Interface/AddOns/XIV_Databar/core.lua:265: attempt to call method 'IsVisible' (a nil value)
[string "@Interface/AddOns/XIV_Databar/core.lua"]:265: in function <Interface/AddOns/XIV_Databar/core.lua:261>
[string "=[C]"]: ?

Locals:
_ = XIV_Databar {
 0 = <userdata>
}
event = "PLAYER_REGEN_ENABLED"
(*temporary) = nil
(*temporary) = <table> {
 defaults = <table> {
 }
 ResetUI = <function> defined @Interface/AddOns/XIV_Databar/core.lua:390
 HoverColors = <function> defined @Interface/AddOns/XIV_Databar/core.lua:184
 HexToRGBA = <function> defined @Interface/AddOns/XIV_Databar/core.lua:341
 modules = <table> {
 }
 baseName = "XIV_Databar"
 IterateEmbeds = <function> defined @Interface/AddOns/XIV_Databar/Libs/AceAddon-3.0/AceAddon-3.0.lua:438
 GetColor = <function> defined @Interface/AddOns/XIV_Databar/core.lua:168
 fontFlags = <table> {
 }
 GetTextColorOptions = <function> defined @Interface/AddOns/XIV_Databar/core.lua:588
 RegisterFrame = <function> defined @Interface/AddOns/XIV_Databar/core.lua:198
 Printf = <function> defined @Interface/AddOns/XIV_Databar/Libs/AceConsole-3.0/AceConsole-3.0.lua:65
 SetDefaultModulePrototype = <function> defined @Interface/AddOns/XIV_Databar/Libs/AceAddon-3.0/AceAddon-3.0.lua:405
 GetHeight = <function> defined @Interface/AddOns/XIV_Databar/core.lua:278
 defaultModuleState = true
 IsEnabled = <function> defined @Interface/AddOns/XIV_Databar/Libs/AceAddon-3.0/AceAddon-3.0.lua:447
 DisableModule = <function> defined @Interface/AddOns/XIV_Databar/Libs/AceAddon-3.0/AceAddon-3.0.lua:346
 GetFont = <function> defined @Interface/AddOns/XIV_Databar/core.lua:324
 PrintTable = <function> defined @Interface/AddOns/XIV_Databar/core.lua:349
 RegisterMessage = <function> defined @Interface/AddOns/BugSack/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:90
 GetArgs = <function> defined @Interface/AddOns/XIV_Databar/Libs/AceConsole-3.0/AceConsole-3.0.lua:140
 frames = <table> {
 }
 miniTextPosition = "TOP"
 db = <table> {
 }
 modulesOptionFrame = Frame {
 }
 SetEnabledState = <function> defined @Interface/AddOns/XIV_Databar/Libs/AceAddon-3.0/AceAddon-3.0.lua:420
 enabledState = true
 RegisterEvent = <function> defined @Interface/AddOns/BugSack/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:90
 IterateModules = <function> defined @Interface/AddOns/XIV_Databar/Libs/AceAddon-3.0/AceAddon-3.0.lua:433
 GetClassColors = <function> defined @Interface/AddOns/XIV_Databar/core.lua:328
 SetColor = <function> defined @Interface/AddOns/XIV_Databar/core.lua:159
 OnInitialize = <function> defined @Interface/AddOns/XIV_Databar/core.lua:81
 NewModule = <function> defined @Interface/AddOns/XIV_Databar/Libs/AceAddon-3.0/AceAddon-3.0.lua:231
 GetModule = <function> defined @Interface/AddOns/XIV_Databar/Libs/AceAddon-3.0/AceAddon-3.0.lua:206
 defaultModuleLibraries = <table> {
 }
 optionsFrame = Frame {
 }
 GetTextOptions = <function> defined @Interface/AddOns/XIV_Databar/core.lua:538
 UnregisterChatCommand = <function> defined @Interface/AddOns/XIV_Databar/Libs/AceConsole-3.0/AceConsole-3.0.lua:107
 GetName = <function> defined @Interface/AddOns/XIV_Databar/Libs/AceAddon-3.0/AceAddon-3.0.lua:275
 name = "XIV_Databar"
 HideBarEvent = <function> defined @Interface/AddOns/XIV_Databar/core.lua:219
 orderedModules = <table> {
 }
 CreateMainBar = <function> defined @Interface/AddOns/XIV_Databar/core.lua:212
 Disable = <function> defined @Interface/AddOns/XIV_Databar/Libs/AceAddon-3.0/AceAddon-3.0.lua:310
 LSM = <table> {
 }
 Print = <function> defined @Interface/AddOns/XIV_Databar/Libs/AceConsole-3.0/AceConsole-3.0.lua:50
 constants = <table> {
 }
 IsModule = <function> defined @Interface/AddOns/XIV_Databar/Libs/AceAddon-3.0/AceAddon-3.0.lua:464
 SendMessage = <function> defined @Interface/AddOns/BugSack/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:59
 timerRefresh = true
 profilesOptionFrame = Frame {
 }
 OnEnable = <function> defined @Interface/AddOns/XIV_Databar/core.lua:137
 SetDefaultModuleLibraries = <function> defined @Interface/AddOns/XIV_Databar/Libs/AceAddon-3.0/AceAddon-3.0.lua:363
 Enable = <function> defined @Interface/AddOns/XIV_Databar/Libs/AceAddon-3.0/AceAddon-3.0.lua:290
 RegisterChatCommand = <function> defined @Interface/AddOns/XIV_Databar/Libs/AceConsole-3.0/AceConsole-3.0.lua:81
 EnableModule = <function> defined @Interface/AddOns

-------------------------------------------------------------------------------------------------------------------------------
1x Interface/AddOns/XIV_Databar/core.lua:233: attempt to call method 'IsVisible' (a nil value)
[string "@Interface/AddOns/XIV_Databar/core.lua"]:233: in function <Interface/AddOns/XIV_Databar/core.lua:230>
[string "=[C]"]: ?

Locals:
_ = XIV_Databar {
 0 = <userdata>
}
event = "VEHICLE_POWER_SHOW"
(*temporary) = nil
(*temporary) = <table> {
 defaults = <table> {
 }
 ResetUI = <function> defined @Interface/AddOns/XIV_Databar/core.lua:390
 HoverColors = <function> defined @Interface/AddOns/XIV_Databar/core.lua:184
 HexToRGBA = <function> defined @Interface/AddOns/XIV_Databar/core.lua:341
 modules = <table> {
 }
 baseName = "XIV_Databar"
 IterateEmbeds = <function> defined @Interface/AddOns/XIV_Databar/Libs/AceAddon-3.0/AceAddon-3.0.lua:438
 GetColor = <function> defined @Interface/AddOns/XIV_Databar/core.lua:168
 fontFlags = <table> {
 }
 GetTextColorOptions = <function> defined @Interface/AddOns/XIV_Databar/core.lua:588
 RegisterFrame = <function> defined @Interface/AddOns/XIV_Databar/core.lua:198
 Printf = <function> defined @Interface/AddOns/XIV_Databar/Libs/AceConsole-3.0/AceConsole-3.0.lua:65
 SetDefaultModulePrototype = <function> defined @Interface/AddOns/XIV_Databar/Libs/AceAddon-3.0/AceAddon-3.0.lua:405
 GetHeight = <function> defined @Interface/AddOns/XIV_Databar/core.lua:278
 defaultModuleState = true
 IsEnabled = <function> defined @Interface/AddOns/XIV_Databar/Libs/AceAddon-3.0/AceAddon-3.0.lua:447
 DisableModule = <function> defined @Interface/AddOns/XIV_Databar/Libs/AceAddon-3.0/AceAddon-3.0.lua:346
 GetFont = <function> defined @Interface/AddOns/XIV_Databar/core.lua:324
 PrintTable = <function> defined @Interface/AddOns/XIV_Databar/core.lua:349
 RegisterMessage = <function> defined @Interface/AddOns/BugSack/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:90
 GetArgs = <function> defined @Interface/AddOns/XIV_Databar/Libs/AceConsole-3.0/AceConsole-3.0.lua:140
 frames = <table> {
 }
 miniTextPosition = "TOP"
 db = <table> {
 }
 modulesOptionFrame = Frame {
 }
 SetEnabledState = <function> defined @Interface/AddOns/XIV_Databar/Libs/AceAddon-3.0/AceAddon-3.0.lua:420
 enabledState = true
 RegisterEvent = <function> defined @Interface/AddOns/BugSack/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:90
 IterateModules = <function> defined @Interface/AddOns/XIV_Databar/Libs/AceAddon-3.0/AceAddon-3.0.lua:433
 GetClassColors = <function> defined @Interface/AddOns/XIV_Databar/core.lua:328
 SetColor = <function> defined @Interface/AddOns/XIV_Databar/core.lua:159
 OnInitialize = <function> defined @Interface/AddOns/XIV_Databar/core.lua:81
 NewModule = <function> defined @Interface/AddOns/XIV_Databar/Libs/AceAddon-3.0/AceAddon-3.0.lua:231
 GetModule = <function> defined @Interface/AddOns/XIV_Databar/Libs/AceAddon-3.0/AceAddon-3.0.lua:206
 defaultModuleLibraries = <table> {
 }
 optionsFrame = Frame {
 }
 GetTextOptions = <function> defined @Interface/AddOns/XIV_Databar/core.lua:538
 UnregisterChatCommand = <function> defined @Interface/AddOns/XIV_Databar/Libs/AceConsole-3.0/AceConsole-3.0.lua:107
 GetName = <function> defined @Interface/AddOns/XIV_Databar/Libs/AceAddon-3.0/AceAddon-3.0.lua:275
 name = "XIV_Databar"
 HideBarEvent = <function> defined @Interface/AddOns/XIV_Databar/core.lua:219
 orderedModules = <table> {
 }
 CreateMainBar = <function> defined @Interface/AddOns/XIV_Databar/core.lua:212
 Disable = <function> defined @Interface/AddOns/XIV_Databar/Libs/AceAddon-3.0/AceAddon-3.0.lua:310
 LSM = <table> {
 }
 Print = <function> defined @Interface/AddOns/XIV_Databar/Libs/AceConsole-3.0/AceConsole-3.0.lua:50
 constants = <table> {
 }
 IsModule = <function> defined @Interface/AddOns/XIV_Databar/Libs/AceAddon-3.0/AceAddon-3.0.lua:464
 SendMessage = <function> defined @Interface/AddOns/BugSack/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:59
 timerRefresh = true
 profilesOptionFrame = Frame {
 }
 OnEnable = <function> defined @Interface/AddOns/XIV_Databar/core.lua:137
 SetDefaultModuleLibraries = <function> defined @Interface/AddOns/XIV_Databar/Libs/AceAddon-3.0/AceAddon-3.0.lua:363
 Enable = <function> defined @Interface/AddOns/XIV_Databar/Libs/AceAddon-3.0/AceAddon-3.0.lua:290
 RegisterChatCommand = <function> defined @Interface/AddOns/XIV_Databar/Libs/AceConsole-3.0/AceConsole-3.0.lua:81
 EnableModule = <function> defined @Interface/AddOns/X

**Comment by Kozoaku** [comment]
Please download the latest beta release from [Wago](https://addons.wago.io/addons/xiv-databar/versions?stability=beta) and make sure the bug you described is fixed.
