### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ThePrez0Dent** [Kozoaku/XIV_Databar#50]
**Can't really make sense of what is happening here**

1x [ADDON_ACTION_BLOCKED] AddOn 'XIV_Databar' tried to call the protected function 'UIParentRightManagedFrameContainer:SetPoint()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetPoint'
[string "@SharedXML/AnchorUtil.lua"]:34: in function `SetPoint'
[string "@FrameXML/UIParent.lua"]:3095: in function `UIParentManageFramePositions'
[string "@FrameXML/UIParent.lua"]:2570: in function <FrameXML/UIParent.lua:2557>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML/UIParent.lua"]:3113: in function `UIParent_ManageFramePositions'
[string "@Blizzard_ObjectiveTracker/Blizzard_ObjectiveTracker.lua"]:1470: in function <...zzard_ObjectiveTracker/Blizzard_ObjectiveTracker.lua:1365>
[string "=[C]"]: in function `ObjectiveTracker_Update'
[string "@Blizzard_ObjectiveTracker/Blizzard_ObjectiveTracker.lua"]:973: in function <...zzard_ObjectiveTracker/Blizzard_ObjectiveTracker.lua:876>

**Comment by Kozoaku** [comment]
I'm not sure what caused this. The code anchors to the UIParent using SetPoint but doesn't try to manipulate the ObjectiveTracker.

I am trying to replicate so if you remember how you got it to pop up or it happens again, please reply here.

**Comment by ThePrez0Dent** [comment]
I am still trying to narrow down the exact moment when the error message triggers.
I will get back to you if I manage to do so

**Comment by Kozoaku** [comment]
I'm going to close this since I can't replicate it to figure out how to fix. If it happens again, just re-open this or create a new issue.
