### ISSUE TITLE
SetText

### ISSUE THREAD

**Issue by kswebdev** [Kozoaku/XIV_Databar#51]
290x FontString:SetText(): Font not set
[string "=[C]"]: in function `SetText'
[string "@XIV_Databar/modules/armor.lua"]:243: in function `UpdatePlayerCoordinates'
[string "@XIV_Databar/modules/armor.lua"]:108: in function <XIV_Databar/modules/armor.lua:106>

**Comment by kswebdev** [comment]
I believe it was happening everywhere. I will check and get you more information.

Sent via the Samsung Galaxy Z Fold4, an AT&T 5G smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by RinJJ** [comment]
I am getting something similar everywhere.
While I have next to 0 coding knowledge for now. It does seem like there a few bugs that stem from a similar issue and maybe them together would help elucidate the matter. I am sorry that it is wordy I just tried to compile the info as best as I could and
To my severely untrained eye it seems that there is maybe? a string issue with pulling/calling text and fonts from the blizzard GUIs to the modules as well as possibly the general settings of XiV_DB to its respective modules. I have quite a few bug reports but I don't explicitly understand most of what I am looking at.


> FontString:SetText(): Font not set
[string "=[C]"]: in function `SetText'
[string "@XIV_Databar/modules/micromenu.lua"]:439: in function `?'
[string "@Ace3/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:114: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:114>
[string "=[C]"]: ?
[string "@Ace3/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:24: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:20>
[string "@Ace3/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:59: in function `Fire'
[string "@Ace3/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>

I am also getting an error code similar to the OP's and another issue that may be similar whereHookScript is not allowed on LibQTip like it was in previous patches as stated in this post on https://www.wowinterface.com/forums/showthread.php?t=59247
With what I would assume are issues "calling" to various interface elements namely issues pertaining to the Microbar Module and the Armor Module where it is having issue pulling info off of the item info for the Armor % amounts and Coordinate Numbers. As well as the added issues of mine where just setting the text that overlays the social buttons and display for guild information was failing.

Also not sure if this is what is causing it not to load at all on zone in's and reloads until I reset XiV_DB from and to Fullscreen and back in the general menu but if any information helps I have a few error codes that I can just list below that I have no clue even coincide with the issue and maybe another on its own.

> XIV_Databar/core.lua:380: attempt to call global 'PlayerFrame_IsAnimatedOut' (a nil value)
[string "@XIV_Databar/core.lua"]:380: in function `OffsetUI'
[string "@XIV_Databar/core.lua"]:310: in function `Refresh'
[string "@XIV_Databar/core.lua"]:156: in function <XIV_Databar/core.lua:154>
[string "=[C]"]: ?
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>
[string "=[C]"]: in function `LoadAddOn'
[string "@FrameXML/UIParent.lua"]:536: in function `UIParentLoadAddOn'
[string "@FrameXML/UIParent.lua"]:741: in function `MajorFactions_LoadUI'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:100: in function `SetUpMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:93: in function `RefreshMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:88: in function `RefreshOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:80: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:76>
[string "=[C]"]: in function `CreateFrame'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:49: in function `CreateOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:63: in function `RefreshExpansionOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:35: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:33>

And to clarify I get both bugs and Login, Zone ins, and Reloads.

Below are bugs when hovering Armor symbol on the Microbar. Which could obviously be and Elvui issue and not XiV_DB but a similar error occurs when elv is turned off as well of which I will post again below with Locale data if it is supplied by bugsack

> HookScript is not allowed on LibQTip tooltips
[string "@ElvUI/Core/General/Toolkit.lua"]:155: in function `SetTemplate'
[string "@XIV_Databar/modules/micromenu.lua"]:103: in function `SkinFrame'
[string "@XIV_Databar/modules/micromenu.lua"]:525: in function <XIV_Databar/modules/micromenu.lua:504>

Below is when Elvui is turned off

> 381x FontString:SetText(): Font not set
[string "=[C]"]: in function `SetText'
[string "@XIV_Databar/modules/armor.lua"]:243: in function `UpdatePlayerCoordinates'
[string "@XIV_Databar/modules/armor.lua"]:108: in function <XIV_Databar/modules/armor.lua:106>

With Locale info

> (*temporary) = FontString {
 0 = <userdata>
}
(*temporary) = "61.3, 65.44"


And then there is the below error when it seems to hover over guild and maybe the Friends tab I could not tell but seems to have to do with Bnet friends? I have locale Information that I will post below it  but censor at least the players personal account info with "~~~"

> XIV_Databar/modules/micromenu.lua:566: attempt to call global 'BNet_GetClientTexture' (a nil value)
[string "@XIV_Databar/modules/micromenu.lua"]:566: in function <XIV_Databar/modules/micromenu.lua:504>

and the locale info

> charName = "~~~"
gameClient = "WoW"
realmName = "Kel'Thuzad"
faction = "Alliance"
zone = "Valdrakken"
richPresence = "Valdrakken - Kel'Thuzad"
isWoW = false
isClassic = false
statusIcon = "Interface\FriendsFrame\StatusIcon-Online"
(*temporary) = nil
(*temporary) = "WoW"
(*temporary) = "attempt to call global 'BNet_GetClientTexture' (a nil value)" 

Again which all of this I would assume, albeit with next to zero real knowledge, to be due changes made recently to the way Calling/Callback and or Hooking information has been changed recently. 

I am not a coder, just a soon to be student and gave it my college try assess the info I saw and someone who likes the way the addon looks over the poopy looking Databars that Elvui has.

And big thanks again to you Kozoaku for continuing this. I personally don't now how much work it is too maintain these things when there are changes but I am sure it is no small amount and I am sure I will soon find how in the coming months myself.

**Comment by Kozoaku** [comment]
This was fixed as part of the social icon updates and Blizz's change to using Atlas.
