### ISSUE TITLE
Volume Module Error

### ISSUE THREAD

**Issue by ThePrez0Dent** [Kozoaku/XIV_Databar#59]
Following Error happens when you have the volume module enabled but use a keybind to to raise/lower the ingame master volume

2x XIV_Databar/modules/mastervolume.lua:143: attempt to index local 'self' (a nil value)
[string "@XIV_Databar/modules/mastervolume.lua"]:143: in function <XIV_Databar/modules/mastervolume.lua:139>
[string "=[C]"]: in function `Sound_MasterVolumeDown'
[string "MASTERVOLUMEDOWN"]:1: in function <[string "MASTERVOLUMEDOWN"]:1>

Locals:
self = nil
volume = 0.100000
volumePercent = 10
volumePercentTrimed = 10
(*temporary) = "10.0"
(*temporary) = 10
(*temporary) = 10
(*temporary) = "10.0"
(*temporary) = "attempt to index local 'self' (a nil value)"

**Comment by Kozoaku** [comment]
Fix is in beta version.
