### ISSUE TITLE
XP Bar Color

### ISSUE THREAD

**Issue by ThePrez0Dent** [Kozoaku/XIV_Databar#63]
Hate to do this to you again 

**1. XP Bar appears empty when using class color**

![XP 1](https://user-images.githubusercontent.com/118535256/227251459-d105e0f7-f90d-485d-b106-587821d305b1.png)
![XP 2](https://user-images.githubusercontent.com/118535256/227251516-e3a8b79c-a148-4b3d-a8e3-096fc8922765.png)

**Comment by Kozoaku** [comment]
This has been merged into beta for further testing.
