### ISSUE TITLE
Since this recent patch been getting quite a few errors on the menu

### ISSUE THREAD

**Issue by Dimmnn** [Kozoaku/XIV_Databar#69]
40x XIV_Databar/modules/micromenu.lua:570: attempt to index field '?' (a nil value)
[string "@XIV_Databar/modules/micromenu.lua"]:570: in function <XIV_Databar/modules/micromenu.lua:507>

Locals:
modifierFunc = <function> defined =[C]:-1
tooltip = Frame {
 0 = <userdata>
 OnBackdropLoaded = <function> defined @SharedXML/Backdrop.lua:152
 GetBackdropColor = <function> defined @SharedXML/Backdrop.lua:390
 key = "SocialToolTip"
 SetBackdropBorderColor = <function> defined @SharedXML/Backdrop.lua:422
 RightEdge = Texture {
 }
 template = "Transparent"
 scrollChild = Frame {
 }
 ApplyBackdrop = <function> defined @SharedXML/Backdrop.lua:294
 backdrop = Frame {
 }
 ClearBackdrop = <function> defined @SharedXML/Backdrop.lua:282
 cell_margin_h = 6
 GetBackdropBorderColor = <function> defined @SharedXML/Backdrop.lua:409
 labelProvider = <table> {
 }
 height = 218.661774
 SetBorderBlendMode = <function> defined @SharedXML/Backdrop.lua:266
 regularFont = GameTooltipText {
 }
 Center = Texture {
 }
 columns = <table> {
 }
 PixelSnapDisabled = true
 BottomEdge = Texture {
 }
 layoutType = "TooltipDefaultLayout"
 cell_margin_v = 3
 headerFont = GameTooltipHeaderText {
 }
 BottomRightCorner = Texture {
 }
 SetupTextureCoordinates = <function> defined @SharedXML/Backdrop.lua:214
 scripts = <table> {
 }
 HasBackdropInfo = <function> defined @SharedXML/Backdrop.lua:278
 BottomLeftCorner = Texture {
 }
 TopRightCorner = Texture {
 }
 scrollFrame = ScrollFrame {
 }
 TopLeftCorner = Texture {
 }
 GetEdgeSize = <function> defined @SharedXML/Backdrop.lua:188
 NineSlice = Frame {
 }
 backdropInfo = <table> {
 }
 TopEdge = Texture {
 }
 isSkinned = true
 TooltipBackdropOnLoad = <function> defined @SharedXML/SharedTooltipTemplates.lua:172
 width = 733.847565
 SetBackdrop = <function> defined @SharedXML/Backdrop.lua:329
 OnBackdropSizeChanged = <function> defined @SharedXML/Backdrop.lua:182
 lines = <table> {
 }
 GetBackdrop = <function> defined @SharedXML/Backdrop.lua:347
 SetupPieceVisuals = <function> defined @SharedXML/Backdrop.lua:246
 SetBackdropColor = <function> defined @SharedXML/Backdrop.lua:399
 LeftEdge = Texture {
 }
 colspans = <table> {
 }
}
_ = 28
totalBNOnlineFriends = 18
totalOnlineFriends = 1
playerFaction = "Horde"
r = 0.768628
g = 0.117647
b = 0.227451
(for index) = 15
(for limit) = 28
(for step) = 1
i = 15
friendAccInfo = <table> {
 isFriend = true
 isDND = false
 isFavorite = false
 gameAccountInfo = <table> {
 }
 accountName = "|Kq9|k"
 battleTag = "Matheney#1544"
 note = ""
 rafLinkType = 0
 bnetAccountID = 1
 appearOffline = false
 customMessage = ""
 lastOnlineTime = 1679263125
 customMessageTime = 0
 isAFK = false
 isBattleTagFriend = true
}
gameAccount = <table> {
 isGameAFK = false
 clientProgram = "Fen"
 richPresence = "In Gnarled Timbers - Fractured Peaks"
 isGameBusy = false
 gameAccountID = 50
 isWowMobile = false
 isInCurrentRegion = false
 regionID = 72
 hasFocus = true
 canSummon = false
 isOnline = true
}
charName = nil
gameClient = "Fen"
realmName = nil
faction = nil
zone = nil
richPresence = "In Gnarled Timbers - Fractured Peaks"
isWoW = false
isClassic = false
statusIcon = "Interface\FriendsFrame\StatusIcon-Online"
socialIcon = "|A:UI-ChatIcon-App:16:16:0:0|a"
(*temporary) = nil
(*temporary) = 16
(*temporary) = 16
(*temporary) = 0
(*temporary) = 0
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "|A:UI-ChatIcon-App:16:16:0:0|a"
(*temporary) = "|A:%s:%d:%d:%d:%d|a"
(*temporary) = "UI-ChatIcon-App"
(*temporary) = 16
(*temporary) = 16
(*temporary) = 0
(*temporary) = 0
(*temporary) = "|A:UI-ChatIcon-App:16:16:0:0|a"
(*temporary) = nil
(*temporary) = "attempt to index field '?' (a nil value)"
xb = <table> {
 defaults = <table> {
 }
 ResetUI = <function> defined @XIV_Databar/core.lua:395
 HoverColors = <function> defined @XIV_Databar/core.lua:184
 HexToRGBA = <function> defined @XIV_Databar/core.lua:346
 modules = <table> {
 }
 baseName = "XIV_Databar"
 IterateEmbeds = <function> defined @Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:438
 GetColor = <function> d

**Comment by Kozoaku** [comment]
The fix is now in the beta version and will be pushed to the release version soon.
