### ISSUE TITLE
Travel Module Bugs + (Feature Suggestion I guess)

### ISSUE THREAD

**Issue by ThePrez0Dent** [Kozoaku/XIV_Databar#72]
If you disable the travel module the system and gold modules also disappear. (after a reload)

-------------
Features suggestion
- with blizzards recent change to the dalaran and garrison hearthstones to become toys would it be possible to add drop down menues for the travel options to show a list of the hearthstones, toys and other class specific travel options?
- as some classes have 4+ travel options now would it be possible to have the option to instead of 2x text have more options but purely as icons?

**Comment by Kozoaku** [comment]
I'm going to close this only so I can separate the work. The travel module needs a lot of work and there is another ticket to make it work better with the toys. I can look into the bug part as part of the 3.1.3 planned release and the feature as part of the 3.2 planned release.

With version 4.0 planning I can take these into consideration as well.

**Comment by Kozoaku** [comment]
See #74 and #75 for tracking of these requests.
